import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const iconScript = `<script>
const svg=(body)=>'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+body+'</svg>';
const icons=[svg('<rect x="3" y="4" width="18" height="13" rx="1.5"/><path d="M8 21h8M12 17v4"/>'),svg('<rect x="2.5" y="5" width="19" height="13" rx="1.5"/><path d="M6 21h12M9 18l-1 3m7-3 1 3"/>'),svg('<path d="M8 7h8a3 3 0 0 1 3 3v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7a3 3 0 0 1 3-3Z"/><path d="M8 4 6.5 2.5M16 4l1.5-1.5M8 12h.01M16 12h.01M9 16h6"/>'),svg('<path d="M12 20c-4.5-2.2-7-5.6-7-9.4A4.6 4.6 0 0 1 12 7a4.6 4.6 0 0 1 7 3.6c0 3.8-2.5 7.2-7 9.4Z"/><path d="M12 7c1.2-1.5 1.3-3 1.2-4 1.6.4 2.7 1.6 2.9 3.1"/>'),svg('<path d="m3 5 8-2v8H3V5Zm10-2 8 2v6h-8V3ZM3 13h8v8l-8-2v-6Zm10 0h8v6l-8 2v-8Z"/>')];
document.querySelectorAll('.platforms b').forEach((el,i)=>el.innerHTML=icons[i]);
const platformImages=['/icons/smart-tv.png','/icons/notebook.png','/icons/android.png','/icons/apple.png','/icons/windows.png'];
document.querySelectorAll('.platforms b').forEach((el,i)=>el.innerHTML='<img src="'+platformImages[i]+'" alt="">');
const wa=document.querySelector('.float-wa'); if(wa) wa.innerHTML=svg('<path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4A8 8 0 1 1 20 11.5Z"/><path d="M8.5 8.3c.2-.4.4-.4.7-.4h.4c.2 0 .3.1.4.4l.7 1.6c.1.2.1.4-.1.6l-.5.5c-.1.1-.1.3 0 .5.4.6 1.1 1.4 2.3 1.9.2.1.4.1.5-.1l.6-.7c.1-.2.3-.2.5-.1l1.5.7c.2.1.2.3.2.5-.1.5-.4 1.1-.8 1.3-.5.3-1.1.2-1.7 0-1.1-.4-2.3-1.1-3.3-2.1-1-1.1-1.6-2.2-1.9-3.1-.2-.6-.2-1.2.5-1.5Z"/>');
</script>`;
const whatsappScript = `<script>const wa=document.querySelector('.float-wa');if(wa)wa.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4A8 8 0 1 1 20 11.5Z"/><path d="M8.5 8.3c.2-.4.4-.4.7-.4h.4c.2 0 .3.1.4.4l.7 1.6c.1.2.1.4-.1.6l-.5.5c-.1.1-.1.3 0 .5.4.6 1.1 1.4 2.3 1.9.2.1.4.1.5-.1l.6-.7c.1-.2.3-.2.5-.1l1.5.7c.2.1.2.3.2.5-.1.5-.4 1.1-.8 1.3-.5.3-1.1.2-1.7 0-1.1-.4-2.3-1.1-3.3-2.1-1-1.1-1.6-2.2-1.9-3.1-.2-.6-.2-1.2.5-1.5Z" fill="#fff" stroke="none"/></svg>';</script>`;
const actionIconScript = `<script>const action=document.querySelector('.hero-actions .primary');if(action)action.innerHTML='<img class="action-icon" src="/icons/assinar-agora.png" alt=""> Assinar Agora';</script>`;
const catalogScript = `<script>const catalog=[['Reacher','Ação'],['O Mentalista','Séries'],['Meu Nome é Farah','Drama'],['Fúria','Suspense'],['Harry Potter','Fantasia'],['Colisão','Drama'],['The Early Spring','Romance'],['O Poderoso Chefão','Clássico'],['Um Sonho de Liberdade','Drama'],['A Lista de Schindler','História'],['Toy Story','Infantil'],['Batman','Ação']];const showcase=document.querySelector('.showcase .wrap');if(showcase){const title=document.createElement('div');title.className='catalog-heading';title.innerHTML='<span class="kicker">MAIS PARA VOCÊ ASSISTIR</span><h2>Histórias que valem a sessão</h2>';const grid=document.createElement('div');grid.className='poster-catalog';catalog.forEach((item,i)=>{const card=document.createElement('article');card.className='catalog-card';card.style.backgroundImage='url(/catalogo-extra-'+(i+1)+'.png)';card.innerHTML='<div><strong>'+item[0]+'</strong><span>'+item[1]+'</span></div>';grid.appendChild(card)});showcase.append(title,grid)}const mosaicImages=['/catalogo-extra-1.png','/catalogo-extra-2.png','/catalogo-extra-3.png','/catalogo-extra-4.png','/catalogo-extra-5.png','/catalogo-extra-6.png','/catalogo-extra-7.png','/catalogo-extra-8.png','/catalogo-extra-9.png','/catalogo-extra-10.png','/catalogo-extra-11.png','/catalogo-extra-12.png'];document.querySelectorAll('.mosaic div').forEach((el,i)=>el.style.backgroundImage='url('+mosaicImages[i%mosaicImages.length]+')');</script>`;
const contentRefreshScript = `<script>const firstPoster=document.querySelector('.poster-catalog .catalog-card');if(firstPoster){firstPoster.style.backgroundImage='url(/homem-aranha-longe-de-casa.png)';const name=firstPoster.querySelector('strong');if(name)name.textContent='Homem-Aranha: Longe de Casa'}const newTitles=[['Vingadores: Ultimato','Ação','13'],['Gladiador','Épico','14'],['Odisseia','Aventura','16'],['A Morte da Esposa do Pastor','Drama','17'],['Operação: Lioness','Ação','18']];const grid=document.querySelector('.poster-catalog');if(grid)newTitles.forEach(item=>{const card=document.createElement('article');card.className='catalog-card';card.style.backgroundImage='url(/catalogo-extra-'+item[2]+'.png)';card.innerHTML='<div><strong>'+item[0]+'</strong><span>'+item[1]+'</span></div>';grid.appendChild(card)});const mosaicImages=['/catalogo-extra-1.png','/catalogo-extra-2.png','/catalogo-extra-3.png','/catalogo-extra-4.png','/catalogo-extra-5.png','/catalogo-extra-6.png','/catalogo-extra-7.png','/catalogo-extra-8.png','/catalogo-extra-9.png','/catalogo-extra-10.png','/catalogo-extra-11.png','/catalogo-extra-12.png','/catalogo-extra-13.png','/catalogo-extra-14.png','/catalogo-extra-15.png','/catalogo-extra-16.png','/catalogo-extra-17.png','/catalogo-extra-18.png'];document.querySelectorAll('.mosaic div').forEach((el,i)=>el.style.backgroundImage='url('+mosaicImages[i%mosaicImages.length]+')');</script>`;
const benefitsScript = `<script>const benefitIcons=['/icons/rocket.png','/icons/server.png','/icons/headset.png','/icons/tv.png','/icons/globe.png','/icons/check.png'];document.querySelectorAll('.benefit-icon').forEach((el,i)=>{el.textContent='';const img=document.createElement('img');img.src=benefitIcons[i];img.alt='';el.appendChild(img)});const deviceIcons=['/icons/device-smart-tv.png','/icons/device-android-tv.png','/icons/device-tv-box.png','/icons/device-android.png','/icons/device-ios.png','/icons/device-windows.png','/icons/device-notebook.png','/icons/device-browser.png'];document.querySelectorAll('.device-icons b').forEach((el,i)=>{el.textContent='';const img=document.createElement('img');img.src=deviceIcons[i];img.alt='';el.appendChild(img)});const categoryIcons=['/icons/category-sports.png','/icons/category-football.png','/icons/category-news.png','/icons/category-movies.png','/icons/category-series.png','/icons/category-kids.png','/icons/category-docs.png'];document.querySelectorAll('.categories span').forEach((el,i)=>{const label=el.textContent.replace(/^[^\\p{L}]*/u,'').trim();el.textContent='';const img=document.createElement('img');img.src=categoryIcons[i];img.alt='';el.append(img,label)});</script>`;
const themeScript = `<script>const nav=document.querySelector('.navbar');if(nav){document.body.classList.add('dark-mode');const t=document.createElement('button');t.className='theme-toggle';t.type='button';t.setAttribute('aria-label','Alternar modo claro e escuro');t.textContent='☾';nav.appendChild(t);t.addEventListener('click',()=>{document.body.classList.toggle('dark-mode');t.textContent=document.body.classList.contains('dark-mode')?'☾':'☼'});}</script>`;
const server = http.createServer((req,res)=>{
  const url = new URL(req.url, 'http://localhost');
  if (url.pathname === '/' || url.pathname === '/index.html') { res.writeHead(200, {'content-type':'text/html; charset=utf-8'}); const html=fs.readFileSync(path.join(root,'local-preview.html'),'utf8'); res.end(html.replace('</body>',iconScript+whatsappScript+actionIconScript+catalogScript+contentRefreshScript+benefitsScript+themeScript+'</body>')); return; }
  if (url.pathname === '/styles.css') { res.writeHead(200, {'content-type':'text/css; charset=utf-8'}); res.end(fs.readFileSync(path.join(root,'app','globals.css'),'utf8').replace(/^@import[^;]+;\s*/gm,'')); return; }
  if (url.pathname === '/cine.css') { res.writeHead(200, {'content-type':'text/css; charset=utf-8','cache-control':'no-cache'}); res.end(fs.readFileSync(path.join(root,'public','cine.css'),'utf8')); return; }
  if (url.pathname === '/homem-aranha-longe-de-casa.png') { res.writeHead(200, {'content-type':'image/png','cache-control':'no-cache'}); res.end(fs.readFileSync(path.join(root,'public','homem-aranha-longe-de-casa.png'))); return; }
  if (url.pathname === '/cine-card.png') { res.writeHead(200, {'content-type':'image/png','cache-control':'no-cache'}); res.end(fs.readFileSync(path.join(root,'public','cine-card.png'))); return; }
  if (/^\/catalogo-(?:\d+|extra-\d+)\.png$/.test(url.pathname)) { const file = path.join(root, 'public', path.basename(url.pathname)); if (fs.existsSync(file)) { res.writeHead(200, {'content-type':'image/png','cache-control':'no-cache'}); res.end(fs.readFileSync(file)); return; } }
  if (/^\/icons\/[a-z-]+\.png$/.test(url.pathname)) { const file = path.join(root, 'public', url.pathname.slice(1)); if (fs.existsSync(file)) { res.writeHead(200, {'content-type':'image/png','cache-control':'no-cache'}); res.end(fs.readFileSync(file)); return; } }
  res.writeHead(404); res.end('Not found');
});
server.listen(Number(process.env.PORT || 3000), '127.0.0.1', () => console.log(`Nexora Play local server: http://localhost:${process.env.PORT || 3000}`));
