'use client';

import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlay, Clapperboard, Headphones, Menu, Monitor, Play, Smartphone, Sparkles, Tablet, Tv, Wifi, X, Zap } from 'lucide-react';

const WHATSAPP_NUMBER = '5511999999999';
const siteConfig = { name: 'Nexora Play', support: 'Atendimento rápido pelo WhatsApp' };

const contentRows = [
  { title: 'Em alta agora', kicker: 'O que todo mundo está assistindo', items: [
    ['Noite de Estreia', 'Filmes', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=85'], ['Entre Linhas', 'Séries', 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=900&q=85'], ['Ponto de Virada', 'Esportes', 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=85'], ['Universo Azul', 'Documentários', 'https://images.unsplash.com/photo-1534791547706-6a6c0f8f3c12?auto=format&fit=crop&w=900&q=85'], ['A Última Pista', 'Filmes', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=85'], ['Depois do Sol', 'Séries', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=85'],
  ] },
  { title: 'Filmes para a sua noite', kicker: 'Grandes histórias, sem complicação', items: [
    ['Horizonte', 'Aventura', 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=85'], ['Fora do Mapa', 'Ação', 'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=900&q=85'], ['O Encontro', 'Drama', 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=900&q=85'], ['Céu de Outubro', 'Romance', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85'], ['A Grande Viagem', 'Família', 'https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=900&q=85'], ['Cidade em Foco', 'Suspense', 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85'],
  ] },
];

const plans = [
  { name: 'Mensal', price: '29,90', period: '30 dias de acesso', note: 'Para experimentar', badge: '', features: ['Filmes e séries', 'Esportes ao vivo', 'Conteúdo infantil', 'Multi-dispositivos', 'Suporte pelo WhatsApp'] },
  { name: 'Trimestral', price: '69,90', period: '90 dias de acesso', note: 'Economize R$ 19,80', badge: 'MAIS ESCOLHIDO', features: ['Tudo do plano mensal', 'Acesso sem interrupção', 'Suporte prioritário', 'Multi-dispositivos', 'Ativação orientada'] },
  { name: 'Semestral', price: '119,90', period: '180 dias de acesso', note: 'Melhor custo-benefício', badge: 'MELHOR VALOR', features: ['Tudo do plano trimestral', 'Mais economia no período', 'Suporte prioritário', 'Multi-dispositivos', 'Ativação orientada'] },
];

const faqs = [
  ['Como funciona?', 'Você escolhe um plano, fala com nosso atendimento pelo WhatsApp e recebe as orientações para começar a assistir.'],
  ['Em quais dispositivos posso assistir?', 'Smart TVs, TV Box, Fire TV, celulares Android e iPhone, tablets e computadores.'],
  ['Preciso instalar algum aplicativo?', 'Nossa equipe orienta você de acordo com o seu dispositivo. A configuração é simples e acompanhada.'],
  ['Quantos dispositivos posso utilizar?', 'O acesso é pensado para você assistir nos dispositivos compatíveis da sua rotina. Fale com o suporte para entender a melhor opção.'],
  ['Como recebo meu acesso?', 'Após a confirmação do plano, nosso atendimento envia os dados e acompanha sua ativação pelo WhatsApp.'],
  ['Existe suporte?', 'Sim. Você conta com suporte pelo WhatsApp durante a configuração e sempre que precisar.'],
];

function whatsappLink(plan?: string) {
  const message = plan ? `Olá! 👋\nVim pelo site e gostaria de contratar o Plano ${plan}.\n\nPode me passar as informações para ativação?` : 'Olá! 👋\nVim pelo site e gostaria de conhecer os planos.\n\nPode me passar as informações?';
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}
function track(event: string, data?: Record<string, string>) { if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent(event, { detail: data })); }
function WhatsAppButton({ label = 'Falar no WhatsApp' }: { label?: string }) { return <a className="whatsapp-button" href={whatsappLink()} target="_blank" rel="noreferrer" onClick={() => track('ClickWhatsApp')}><span className="whatsapp-mark">◔</span>{label}</a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [openFaq, setOpenFaq] = useState<number | null>(0); const [rowIndexes, setRowIndexes] = useState<Record<number, number>>({});
  const shiftRow = (row: number, direction: number, length: number) => setRowIndexes((current) => ({ ...current, [row]: Math.max(0, Math.min((current[row] ?? 0) + direction, length - 4)) }));
  return <main className="site-shell">
    <header className="site-header"><a href="#inicio" className="brand"><span className="brand-dot" /><span>NEXORA <i>PLAY</i></span></a><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}>{[['Início', '#inicio'], ['Conteúdos', '#catalogo'], ['Planos', '#planos'], ['Como funciona', '#como-funciona'], ['Dúvidas', '#faq']].map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><div className="header-actions"><WhatsAppButton /><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'}>{menuOpen ? <X /> : <Menu />}</button></div></header>
    <section id="inicio" className="hero"><div className="hero-art" /><div className="hero-content"><div className="eyebrow"><span className="live-dot" /> ENTRETENIMENTO SEM COMPLICAÇÃO</div><h1>Todo o entretenimento em um só lugar.</h1><p className="hero-copy">Filmes, séries, esportes e muito mais para assistir na TV, celular, computador ou tablet.</p><div className="hero-checks"><span><Check /> Acesso rápido</span><span><Check /> Diversos dispositivos</span><span><Check /> Suporte pelo WhatsApp</span></div><div className="hero-actions"><a className="primary-button" href="#planos" onClick={() => track('ViewPlans')}>Ver planos <ArrowRight /></a><WhatsAppButton /></div><div className="availability"><span className="availability-dot" /> {siteConfig.support}</div></div><div className="hero-scroll"><span /> role para explorar</div></section>
    <section className="proof-strip" aria-label="Benefícios rápidos">{[['+ entretenimento', 'Diversos conteúdos', <Clapperboard key="proof-content" />], ['Multi-dispositivos', 'TV, celular e computador', <Monitor key="proof-devices" />], ['Instalação simples', 'Comece rapidamente', <Zap key="proof-setup" />], ['Suporte', 'Atendimento via WhatsApp', <Headphones key="proof-support" />]].map(([title, text, icon]) => <div className="proof-item" key={title as string}><div className="proof-icon">{icon}</div><div><strong>{title}</strong><span>{text}</span></div></div>)}</section>
    <section id="catalogo" className="catalog-section section-wrap"><div className="section-intro"><div><span className="section-kicker">UM CATÁLOGO PARA CADA MOMENTO</span><h2>Tem conteúdo para todo mundo.</h2></div><p>Descubra histórias, partidas e descobertas para assistir do seu jeito.</p></div>{contentRows.map((row, rowIndex) => { const offset = rowIndexes[rowIndex] ?? 0; return <div className="content-row" key={row.title}><div className="row-heading"><div><h3>{row.title}</h3><span>{row.kicker}</span></div><div className="row-controls"><button aria-label="Voltar" onClick={() => shiftRow(rowIndex, -1, row.items.length)}><ChevronLeft /></button><button aria-label="Avançar" onClick={() => shiftRow(rowIndex, 1, row.items.length)}><ChevronRight /></button></div></div><div className="row-viewport"><div className="row-track" style={{ transform: `translateX(calc(-${offset} * (var(--card-width) + var(--card-gap))))` }}>{row.items.map(([title, category, image], index) => <article className="content-card" key={title}><img src={image} alt="" /><div className="card-gradient" /><div className="card-info"><span>{category}</span><strong>{title}</strong></div>{index === 0 && <span className="card-badge">NEXORA ORIGINAL</span>}</article>)}</div></div></div>; })}</section>
    <section className="devices-section section-wrap"><div className="device-copy"><span className="section-kicker">NA SUA ROTINA</span><h2>Assista onde quiser.</h2><p>Tenha acesso pelo dispositivo que você já utiliza. A configuração é simples e o suporte acompanha você durante a instalação.</p><div className="device-list"><span><Tv /> Smart TV</span><span><Monitor /> Computador</span><span><Smartphone /> Android / iPhone</span><span><Tablet /> Tablet</span></div><a className="text-link" href="#planos">Quero começar <ArrowRight /></a></div><div className="device-stage"><div className="device-glow" /><div className="device-tv"><div className="screen"><div className="screen-play"><Play fill="currentColor" /></div><span>NEXORA <i>PLAY</i></span></div></div><div className="device-phone"><div className="phone-screen"><div className="mini-poster" /><div className="mini-lines" /><div className="mini-lines short" /></div></div><div className="device-tablet"><div className="tablet-screen"><CirclePlay /></div></div></div></section>
    <section id="planos" className="plans-section section-wrap"><div className="section-intro centered"><div><span className="section-kicker">COMECE HOJE</span><h2>Escolha seu plano.</h2><p>Escolha a opção ideal e finalize seu pedido pelo WhatsApp.</p></div></div><div className="plans-grid">{plans.map((plan, index) => <article key={plan.name} className={`plan-card ${index === 1 ? 'featured' : ''}`}>{plan.badge && <span className="plan-badge">{plan.badge}</span>}<div className="plan-top"><span className="plan-name">Plano {plan.name}</span><Sparkles /></div><div className="plan-price"><small>R$</small><strong>{plan.price}</strong><span>/ período</span></div><span className="plan-period">{plan.period}</span><span className="plan-note">{plan.note}</span><div className="plan-divider" /><ul>{plan.features.map((feature) => <li key={feature}><Check /> {feature}</li>)}</ul><a className={index === 1 ? 'primary-button full' : 'secondary-button full'} href={whatsappLink(plan.name)} target="_blank" rel="noreferrer" onClick={() => track('ClickPlan', { plan_name: plan.name, plan_price: plan.price, plan_period: plan.period })}>Escolher {plan.name} <ArrowRight /></a></article>)}</div><p className="reassurance"><Check /> Atendimento rápido <Check /> Contratação pelo WhatsApp <Check /> Escolha em menos de 1 minuto</p></section>
    <section id="como-funciona" className="steps-section section-wrap"><div className="section-intro centered"><div><span className="section-kicker">SEM COMPLICAÇÃO</span><h2>Começar é fácil.</h2></div></div><div className="steps-grid">{[['01', 'Escolha seu plano', 'Selecione a opção que mais combina com você.'], ['02', 'Fale conosco', 'Você será direcionado automaticamente para o WhatsApp.'], ['03', 'Receba seu acesso', 'Nossa equipe orienta você na configuração.']].map(([number, title, text]) => <div className="step" key={number}><span className="step-number">{number}</span><div className="step-line" /><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="benefits-section section-wrap"><div className="section-intro"><div><span className="section-kicker">A EXPERIÊNCIA NEXORA</span><h2>Feito para você aproveitar.</h2></div></div><div className="benefits-grid">{[['Grande variedade', 'Conteúdos para todos os gostos.', <Clapperboard key="benefit-variety" />], ['Qualidade', 'Experiência otimizada para diferentes conexões.', <Wifi key="benefit-quality" />], ['Diversos dispositivos', 'Assista onde preferir.', <Monitor key="benefit-devices" />], ['Suporte', 'Atendimento pelo WhatsApp.', <Headphones key="benefit-support" />], ['Configuração simples', 'Processo rápido e acompanhado.', <Zap key="benefit-setup" />], ['Planos flexíveis', 'Escolha o período que preferir.', <Sparkles key="benefit-flex" />]].map(([title, text, icon]) => <div className="benefit-card" key={title as string}><div className="benefit-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section id="faq" className="faq-section section-wrap"><div className="faq-heading"><span className="section-kicker">AINDA COM DÚVIDAS?</span><h2>Perguntas frequentes.</h2><p>Se não encontrar o que procura, nosso atendimento está a um clique.</p><WhatsAppButton label="Falar com atendimento" /></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'open' : ''}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index}><span>{question}</span><ChevronDown /></button><div className="faq-answer"><p>{answer}</p></div></div>)}</div></section>
    <section className="final-cta section-wrap"><div><span className="section-kicker">SEU PRÓXIMO MOMENTO COMEÇA AQUI</span><h2>Pronto para começar?</h2><p>Escolha seu plano e fale conosco pelo WhatsApp.</p><div className="hero-actions"><a className="primary-button" href="#planos">Ver planos <ArrowRight /></a><WhatsAppButton /></div></div><div className="cta-orbit"><span /><span /><span /></div></section>
    <footer className="site-footer"><div className="footer-top"><div><a href="#inicio" className="brand"><span className="brand-dot" /><span>NEXORA <i>PLAY</i></span></a><p>Entretenimento do seu jeito.</p></div><div className="footer-links"><a href="#inicio">Início</a><a href="#planos">Planos</a><a href="#como-funciona">Como funciona</a><a href="#faq">Dúvidas</a><a href={whatsappLink()} target="_blank" rel="noreferrer">WhatsApp</a></div></div><div className="footer-bottom"><span>© 2026 Nexora Play. Atendimento realizado via WhatsApp.</span><span>Marcas e conteúdos exibidos pertencem aos seus respectivos proprietários.</span></div></footer>
    <a className="floating-whatsapp" href={whatsappLink()} target="_blank" rel="noreferrer" aria-label="Falar no WhatsApp" onClick={() => track('ClickWhatsApp')}><span className="whatsapp-mark">◔</span><span>Falar no WhatsApp</span></a>
  </main>;
}
