'use client';

import { useState } from 'react';
import { Bell, Check, ChevronLeft, ChevronRight, Grid2X2, Heart, Home, Menu, MessageCircle, Play, Plus, Search, Share2, Tv2, UserRound, X } from 'lucide-react';

const WHATSAPP = '5511999999999';
const posters = [
  ['O Protetor', 'Ação', 'https://images.unsplash.com/photo-1533928298208-27ff66555d8d?auto=format&fit=crop&w=700&q=85'], ['Noite de Estreia', 'Filmes', 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=700&q=85'], ['Universo Azul', 'Documentário', 'https://images.unsplash.com/photo-1534791547706-6a6c0f8f3c12?auto=format&fit=crop&w=700&q=85'], ['Entre Linhas', 'Séries', 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=700&q=85'], ['Cidade em Foco', 'Suspense', 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=700&q=85'], ['Ponto de Virada', 'Esportes', 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=700&q=85'], ['Horizonte', 'Aventura', 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=700&q=85'], ['Depois do Sol', 'Romance', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=700&q=85'], ['A Última Pista', 'Filmes', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=700&q=85'], ['O Encontro', 'Drama', 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=700&q=85'],
];
const plans = [{ name: 'Gold', price: '9,99', color: 'gold', features: ['Sem anúncios', 'Até 10 dispositivos', '720p de resolução', '50 downloads'] }, { name: 'Platinum', price: '29,99', color: 'pink', features: ['Filmes e séries ilimitados', 'Até 20 dispositivos', '4K Ultra HD', '800 downloads'] }, { name: 'Diamond', price: '19,99', color: 'diamond', features: ['Filmes ilimitados', 'Até 20 dispositivos', '1080p de resolução', '100 downloads'] }];
function waLink(message = 'Olá! Gostaria de conhecer o Nexora Play.') { return `https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`; }
function WhatsAppIcon() { return <svg className="wa-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11.5" cy="11.5" r="8.2" fill="none" stroke="currentColor" strokeWidth="1.8" /><path d="M5.4 18.7 4.2 21l2.8-.8" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /><path d="M8.7 8.2c.2-.3.4-.3.7-.3h.4c.2 0 .3.1.4.3l.7 1.5c.1.2.1.4-.1.6l-.5.6c-.1.1-.1.3 0 .4.3.5 1.1 1.6 2.7 2.2.2.1.3 0 .4-.1l.6-.8c.1-.2.3-.2.5-.1l1.5.7c.2.1.3.3.2.5-.1.5-.4 1.3-.9 1.5-.5.3-1.1.2-1.7 0-1-.3-2.2-1-3.3-2.1-1-1-1.8-2.3-2.1-3.2-.3-.8-.2-1.5.2-1.7Z" fill="currentColor" /></svg>; }

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false); const [page, setPage] = useState(0);
  const visiblePosters = posters.slice(page * 5, page * 5 + 5).length === 5 ? posters.slice(page * 5, page * 5 + 5) : posters.slice(0, 5);
  return <main className="film-shell">
    <section className="promo"><span>WELCOME TO NEXORA PLAY!</span><small>Seu entretenimento favorito em um só lugar</small></section>
    <div className="platform">
      <aside className={menuOpen ? 'sidebar open' : 'sidebar'}><div className="side-logo"><span>◈</span></div><button className="mobile-close" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X /></button><div className="side-nav"><a className="active" href="#inicio"><Home /></a><a href="#catalogo"><Grid2X2 /></a><a href="#planos"><Tv2 /></a><a href="#lista"><Heart /></a><a href="#faq"><MessageCircle /></a><a href="#compartilhar"><Share2 /></a></div><div className="side-bottom"><a href="#conta"><UserRound /></a></div></aside>
      <div className="platform-main">
        <header className="topbar"><button className="mobile-menu" onClick={() => setMenuOpen(true)} aria-label="Abrir menu"><Menu /></button><nav><a className="selected" href="#inicio">Início</a><a href="#catalogo">Conteúdos</a><a href="#planos">Planos</a><a href="#como-funciona">Como funciona</a><a href="#faq">Dúvidas</a></nav><div className="top-actions"><Search /><Bell /><span className="avatar">N</span></div></header>
        <section id="inicio" className="feature"><div className="feature-copy"><span className="feature-label">NEXORA PLAY ORIGINAL</span><h1>O último grande espetáculo</h1><div className="feature-meta"><span>IMDb RATING</span><span className="stars">★★★★★</span><span>4.6</span></div><p>Filmes, séries, esportes ao vivo e muito mais. Escolha o que assistir e tenha uma experiência completa em todos os seus dispositivos.</p><div className="feature-actions"><a className="pink-button" href={waLink('Olá! Gostaria de solicitar um teste grátis do Nexora Play.')}><Play fill="currentColor" /> Solicite teste grátis</a><button className="round-button" aria-label="Adicionar à minha lista"><Plus /></button></div></div><div className="feature-art" /></section>
        <section id="catalogo" className="recommendations"><div className="section-title"><h2>Recomendações</h2><div className="filters"><button>2026⌄</button><button>Categoria⌄</button><button>Gênero⌄</button><label><Search /><input placeholder="Pesquisar" /></label></div></div><div className="poster-grid">{visiblePosters.map(([title, category, image], index) => <article className="poster-card" key={`${title}-${index}`}><div className="poster-image" style={{ backgroundImage: `url(${image})` }}><span className="poster-plus"><Plus /></span></div><span className="poster-tag">{category}</span><h3>{title}</h3><div className="poster-meta"><span className="stars">★★★★★</span><span>4.{index + 2}</span><span>2026</span></div><a className="poster-cta" href={waLink(`Olá! Tenho interesse em assistir ${title}.`)}>Ver agora</a></article>)}</div><div className="pagination"><button onClick={() => setPage(Math.max(0, page - 1))} aria-label="Página anterior"><ChevronLeft /></button>{[0, 1, 2, 3].map((number) => <button key={number} className={page === number ? 'current' : ''} onClick={() => setPage(number)}>{number + 1}</button>)}<span>...</span><button>25</button><button onClick={() => setPage(Math.min(1, page + 1))} aria-label="Próxima página"><ChevronRight /></button></div></section>
        <section id="planos" className="choose-plan"><div className="section-title centered"><div><h2>Escolha seu plano</h2><p>Assista ao que quiser, quando quiser.</p></div></div><div className="plans-grid">{plans.map((plan, index) => <article className={`film-plan ${plan.color}`} key={plan.name}><span className="plan-orb">{index === 0 ? '✦' : index === 1 ? '◆' : '◇'}</span><h3>{plan.name} Plan</h3><strong><small>$</small>{plan.price}<em>/mês</em></strong><ul>{plan.features.map((feature) => <li key={feature}><Check /> {feature}</li>)}</ul><a className={index === 1 ? 'pink-button full' : 'dark-button full'} href={waLink(`Olá! Quero testar o ${plan.name} Plan do Nexora Play.`)}>Começar teste grátis</a></article>)}</div></section>
        <section id="como-funciona" className="how"><h2>Pronto para começar?</h2><p>Escolha seu plano e fale com nosso atendimento pelo WhatsApp.</p><a className="pink-button" href={waLink('Olá! Gostaria de conhecer os planos do Nexora Play.')}><WhatsAppIcon /> Falar no WhatsApp</a></section>
        <footer id="faq"><span>© 2026 Nexora Play</span><a href={waLink()}>Suporte pelo WhatsApp</a></footer>
      </div>
    </div>
  </main>;
}
